
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MeuCarroCerto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class t_carros_teste
{

    public long codigo { get; set; }

    public int codigo_marcas { get; set; }

    public string nome { get; set; }



    public virtual t_marcas t_marcas { get; set; }

}

}
