
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MeuCarroCerto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class t_carros
{
    private EntidadesMeuCarroCertoDB db = new EntidadesMeuCarroCertoDB();

    public long codigo { get; set; }

    public string nome { get; set; }

    public int codigo_marca { get; set; }

    public int ano { get; set; }

    public int codigo_tipo_carroceria { get; set; }

    public int valor { get; set; }

    public int qtd_ocupantes { get; set; }

    public int trio_eletrico { get; set; }

    public int ar_condicionado { get; set; }

    public int direcao_hidraulica { get; set; }

    public int sensor_de_estacionamento { get; set; }

    public int alarme { get; set; }

    public int cambio_automatico { get; set; }

    public int desempenho_zero_a_cem { get; set; }

    public int central_multimidia { get; set; }

    public int entrada_usb { get; set; }

    public int camera_de_re { get; set; }

    public int farol_neblina { get; set; }

    public int piloto_automatico { get; set; }

    public int roda_liga { get; set; }

    public int teto_solar { get; set; }

    public string historico_fabricante { get; set; }

    public int ano_projeto { get; set; }

    public string rede_concessionaria { get; set; }

    public string disponibilidade_de_pecas { get; set; }

    public int tempo_de_garantia { get; set; }

    public string design { get; set; }

    public int blindagem { get; set; }

    public int banco_de_couro { get; set; }

    public int avaliacao_crash_test { get; set; }

    public int controle_de_tracao { get; set; }

    public int freio_com_EBD { get; set; }

    public int freio_com_BAS { get; set; }

    public int ipva { get; set; }

    public int valor_do_seguro { get; set; }

    public int custo_de_manutencao { get; set; }

    public int conquista { get; set; }

    public int exclusividade { get; set; }

    public int boa_imagem { get; set; }

    public int aventureiro { get; set; }

    public int controle_de_estabilidade_ESP { get; set; }

    public int freio_com_ABS { get; set; }

    public int consumo { get; set; }

    public int airbag { get; set; }

    public string marca_comp { get; set; }

    public virtual t_carrocerias t_carrocerias { get; set; }

    public virtual t_marcas t_marcas { get; set; }

    public void marca()
    {
        var marcasMetadado = db.t_marcas.SqlQuery("select nome from t_marcas where codigo=" + codigo_marca + ";");
         foreach (var item in marcasMetadado)
            {
                marca_comp = item.nome;
            }
        
    }

}

}
