
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MeuCarroCerto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class t_cores
{

    public t_cores()
    {

        this.t_carros = new HashSet<t_carros>();

    }


    public long codigo { get; set; }

    public string nome { get; set; }



    public virtual ICollection<t_carros> t_carros { get; set; }

}

}
