
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MeuCarroCerto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class t_marcas
{

    public t_marcas()
    {

        this.t_carros_teste = new HashSet<t_carros_teste>();

    }


    public int codigo { get; set; }

    public string nome { get; set; }



    public virtual ICollection<t_carros_teste> t_carros_teste { get; set; }

}

}
